version: '3.8'
services:
  backend:
    build: ../backend
    ports:
      - "5000"
    networks:
      - deployboard-network
  
  frontend:
    build: ../frontend/deployboard-ui
    ports:
      - "80:80"
    networks:
      - deployboard-network

networks:
  deployboard-network:
    driver: bridge